# Generated by Django 4.0.5 on 2022-07-13 11:48

import church.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_alter_lesson_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='body',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Notes',
            field=models.FileField(blank=True, upload_to=church.models.save_lesson_files, verbose_name='Notes'),
        ),
    ]
