# Generated by Django 4.0.5 on 2022-07-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_remove_lesson_body_lesson_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='Notes',
        ),
        migrations.AddField(
            model_name='lesson',
            name='body',
            field=models.TextField(blank=True, max_length=500, verbose_name='body'),
        ),
    ]
