# Generated by Django 4.0.5 on 2022-07-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_alter_lesson_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='body2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body3',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body4',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body5',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body6',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='body7',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='body',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
