# Generated by Django 4.0.5 on 2022-07-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0016_alter_lesson_body_alter_lesson_body2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
