# Generated by Django 4.0.5 on 2022-07-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_sundaysermon_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundaysermon',
            name='body2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sundaysermon',
            name='body3',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
