# Generated by Django 4.0.5 on 2022-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0026_weeklyprayersmotivations'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyprayersmotivations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images_uploaded'),
        ),
    ]
