# Generated by Django 4.0.5 on 2022-06-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_alter_blog_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='image',
            field=models.ImageField(null=True, upload_to='images_uploaded'),
        ),
    ]
