# Generated by Django 4.0.5 on 2022-06-25 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_blog_post_image_alter_blog_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_post',
            name='video',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Commenter', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.blog_post')),
            ],
        ),
    ]
