# Generated by Django 4.0.5 on 2022-07-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
