# Generated by Django 4.0.5 on 2022-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_upcomingevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='birthdaydate',
            field=models.DateField(null=True),
        ),
    ]
