# Generated by Django 4.0.5 on 2022-07-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_userprofileinfo_birthdaydate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='birthdaydate',
        ),
    ]
